import React, { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { calculateFare, PaymentMethod } from './fare';
import { passengerScreens, PassengerScreenId } from './navigation';

const RED = '#ef1720';
const YELLOW = '#ffc515';
const GREEN = '#32b86b';
const money = (value: number) => `${value.toLocaleString('en-US')} MMK`;

export function PassengerApp() {
  const [screen, setScreen] = useState<PassengerScreenId>('Splash');
  const [distance, setDistance] = useState('2.4');
  const [payment, setPayment] = useState<PaymentMethod>('CASH');
  const [credits, setCredits] = useState('0');
  const [safetyOpen, setSafetyOpen] = useState(false);
  const definition = passengerScreens.find((item) => item.id === screen)!;
  const fare = useMemo(
    () => calculateFare(Math.max(0.1, Number(distance) || 0.1), payment, Math.max(0, Math.floor(Number(credits) || 0))),
    [distance, payment, credits],
  );
  const open = (next: PassengerScreenId) => setScreen(next);

  if (screen === 'Splash') {
    return <SafeAreaView style={styles.splash}>
      <View style={styles.mark}><View style={styles.markCore}><Text style={styles.markCar}>TAXI</Text></View><View style={styles.shield}><Text style={styles.shieldCheck}>L</Text></View></View>
      <Text style={styles.splashBrand}>LABAR</Text><Text style={styles.splashTagline}>Your ride, our care.</Text><Text style={styles.splashPlace}>Yangon, Myanmar</Text>
      <Primary label="Start riding" onPress={() => open('Home')} />
    </SafeAreaView>;
  }

  return <SafeAreaView style={styles.safe}>
    <View style={styles.header}>
      {screen !== 'Home' && <Pressable accessibilityRole="button" onPress={() => open('Home')}><Text style={styles.back}>‹</Text></Pressable>}
      <Text style={styles.headerTitle}>{definition.title}</Text>
      <Pressable accessibilityRole="button" onPress={() => open('Notifications')}><View style={styles.notificationDot} /></Pressable>
    </View>
    <ScrollView contentContainerStyle={styles.content}>
      <ScreenContent screen={screen} open={open} fare={fare} distance={distance} setDistance={setDistance} payment={payment} setPayment={setPayment} credits={credits} setCredits={setCredits} safetyOpen={safetyOpen} setSafetyOpen={setSafetyOpen} />
    </ScrollView>
    <BottomNav current={screen} open={open} />
  </SafeAreaView>;
}

type ContentProps = {
  screen: PassengerScreenId; open: (screen: PassengerScreenId) => void;
  fare: ReturnType<typeof calculateFare>; distance: string; setDistance: (value: string) => void;
  payment: PaymentMethod; setPayment: (value: PaymentMethod) => void;
  credits: string; setCredits: (value: string) => void;
  safetyOpen: boolean; setSafetyOpen: (value: boolean) => void;
};

function ScreenContent(p: ContentProps) {
  switch (p.screen) {
    case 'Home': return <><Text style={styles.hero}>Where do you <Text style={styles.red}>want to go?</Text></Text><SearchField /><QuickPlaces /><Section title="Recent places" /><Row title="Tawma Ocean" detail="Tamwe, Yangon" action="" /><Row title="Yangon International Airport" detail="Mingaladon, Yangon" action="" /><Row title="Junction City" detail="Bahan, Yangon" action="" /><Row title="Invite friends" detail="Get 1,000 promo credits after their first ride" action="Share" onPress={() => p.open('Promotions')} /><Primary label="Start a ride" onPress={() => p.open('PickupMap')} /></>;
    case 'PickupMap': return <><MapPanel /><Section title="Where are you going?" subtitle="Confirm the pickup entrance and destination." /><Row title="Pickup" detail="My current location, Sanchaung" action="Edit" /><Row title="Destination" detail="Tawma Ocean, Tamwe" action="Edit" /><Primary label="Confirm route" onPress={() => p.open('RouteFees')} /></>;
    case 'RouteFees': return <><MapPanel /><StatBar items={[[`${p.distance} km`,'Distance'],['31 min','Duration'],[money(p.fare.subtotalMMK),'Estimated fare']]} /><TextInput style={styles.input} keyboardType="decimal-pad" value={p.distance} onChangeText={p.setDistance} accessibilityLabel="Route distance in kilometres" /><FareCard fare={p.fare} payment={p.payment} /><Primary label="See ride options" onPress={() => p.open('ChooseRide')} /></>;
    case 'ChooseRide': return <><Section title="Choose a ride" subtitle="All prices include the LaBar service fee." /><RideOption active title="Standard" detail="Good choice of price and comfort · 3 min" price={p.fare.subtotalMMK} /><RideOption title="Comfort" detail="More comfort, newer vehicle · 10 min" price={p.fare.subtotalMMK + 2000} /><RideOption title="Premium" detail="High-end vehicle · 20 min" price={p.fare.subtotalMMK + 6700} /><RideOption title="XL" detail="For larger groups · 32 min" price={p.fare.subtotalMMK + 8700} /><RideOption title="EV" detail="Eco-friendly ride · 31 min" price={p.fare.subtotalMMK + 200} /><Primary label="Continue with Standard" onPress={() => p.open('Payment')} yellow /></>;
    case 'Payment': return <><Section title="Payment method" subtitle={`Estimated fare ${money(p.fare.payableMMK)}`} />{(['CASH','KBZPAY','WAVEPAY','AYAPAY'] as PaymentMethod[]).map((method) => <PaymentRow key={method} method={method} active={p.payment === method} onPress={() => p.setPayment(method)} />)}<Text style={styles.fieldLabel}>LaBar promo credits · 1 credit = 10 MMK</Text><TextInput style={styles.input} keyboardType="number-pad" value={p.credits} onChangeText={p.setCredits} accessibilityLabel="LaBar promo credits" /><FareCard fare={p.fare} payment={p.payment} /><Primary label="Confirm Standard" onPress={() => p.open('FindingDriver')} yellow /></>;
    case 'FindingDriver': return <><Section title="Finding your driver" subtitle="This will not take long." centered /><SearchRings /><Row title="Searching nearby drivers" detail="Finding the best verified match" action="15s" /><Primary label="Simulate driver accepted" onPress={() => p.open('DriverOnTheWay')} yellow /><Secondary label="Cancel search" onPress={() => p.open('Home')} /></>;
    case 'DriverOnTheWay': return <><MapPanel /><View style={styles.eta}><Text style={styles.etaBig}>3 min</Text><Text style={styles.small}>Arriving</Text></View><DriverCard /><View style={styles.plate}><Text style={styles.plateText}>YGN 7N-1234</Text></View><Primary label="View driver details" onPress={() => p.open('DriverDetails')} /><Secondary label="Share trip" onPress={() => p.open('GuardianPlugin')} /></>;
    case 'DriverDetails': return <><DriverCard large /><Vehicle /><Row title="98% safety rating" detail="Your safety is our priority" action="Verified" /><Row title="Licensed and insured" detail="Commercial licence checked" action="Valid" /><Row title="Background checked" detail="Identity and records reviewed" action="Clear" /><Primary label="Start trip" onPress={() => p.open('OnTrip')} /></>;
    case 'OnTrip': return <><MapPanel /><DriverCard /><StatBar items={[[`${p.distance} km`,'Distance'],['21 min','ETA'],[money(p.fare.payableMMK),'Current total']]} /><Row title="Guardian active" detail="Live route shared with trusted contacts" action="On" /><Secondary label="Safety and emergency options" onPress={() => p.setSafetyOpen(!p.safetyOpen)} />{p.safetyOpen && <View style={styles.alert}><Text style={styles.cardTitle}>Discreet Safety Drawer</Text><Text style={styles.detail}>Hold to send silent SOS and share live evidence.</Text><Primary label="Hold for silent SOS" onPress={() => undefined} /></View>}<Primary label="Simulate arrival" onPress={() => p.open('TripComplete')} /></>;
    case 'TripComplete': return <><View style={styles.success}><Text style={styles.successCheck}>✓</Text><Text style={styles.title}>Trip completed</Text><Text style={styles.detail}>Thank you for riding with LaBar.</Text></View><StatBar items={[[`${p.distance} km`,'Distance'],['31 min','Duration'],['Tawma Ocean','Destination']]} /><FareCard fare={p.fare} payment={p.payment} /><DriverCard /><Primary label="Done" onPress={() => p.open('Home')} /></>;
    case 'MyTrips': return <><Tabs labels={['All','Completed','Cancelled']} /><Row title="Tawma Ocean" detail="Today · 10:34 AM" action={money(p.fare.payableMMK)} /><Row title="Junction City" detail="18 Aug · 24 min" action="7,800 MMK" /><Row title="YIA Airport" detail="16 Aug · 48 min" action="14,500 MMK" /><Row title="Inya Lake" detail="14 Aug · 22 min" action="8,600 MMK" /></>;
    case 'Wallet': return <><View style={styles.wallet}><Text style={styles.walletLabel}>LaBar Wallet</Text><Text style={styles.walletBalance}>98,400 MMK</Text><Text style={styles.walletLabel}>Promo balance · 1,240 credits</Text></View><Section title="Quick actions" /><Tabs labels={['Add money','Send money','Promo']} /><Section title="Recent transactions" /><Row title="Top up from KBZPay" detail="18 Aug" action="+10,000" /><Row title="Trip to Tawma Ocean" detail="18 Aug" action="-6,500" /><Row title="Promo reward" detail="16 Aug" action="+1,000" /></>;
    case 'Profile': return <><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>SH</Text></View><Text style={styles.cardTitle}>Stephen Htut</Text><Text style={styles.detail}>+95 12 34 00</Text></View><Row title="Personal information" detail="Name, phone, email" action="›" /><Row title="Payment methods" detail="Cash and wallets" action="›" /><Row title="Saved places" detail="Home, Work, favourites" action="›" /><Row title="LaBar Guardian" detail="Trusted contacts and sharing" action="›" onPress={() => p.open('GuardianPlugin')} /><Row title="Notifications" detail="Trips, promos, system" action="›" onPress={() => p.open('Notifications')} /><Row title="Settings" detail="Language and security" action="›" onPress={() => p.open('Settings')} /></>;
    case 'GuardianPlugin': return <><View style={styles.guardian}><Text style={styles.guardianShield}>L</Text></View><Section title="LaBar Guardian" subtitle="Your safety, our priority." centered /><Row title="Live trip sharing" detail="Only while a ride is active" action="On" /><Row title="Trusted contacts" detail="Two people paired" action="Manage" /><Row title="Emergency assistance" detail="Silent SOS and escalation" action="Ready" /><Row title="Route monitoring" detail="Deviation and long-stop alerts" action="On" /><Primary label="Go to Guardian Center" onPress={() => undefined} /></>;
    case 'SavedPlaces': return <><Tabs labels={['Favourites','Recent']} /><Row title="Home" detail="Sanchaung, Yangon" action="Edit" /><Row title="Work" detail="Sule Square, Yangon" action="Edit" /><Row title="Junction City" detail="Bahan, Yangon" action="Edit" /><Row title="Yangon International Airport" detail="Mingaladon, Yangon" action="Edit" /><Primary label="Add new place" onPress={() => undefined} /></>;
    case 'Notifications': return <><Tabs labels={['All','Trips','Promos','System']} /><Row title="Driver on the way" detail="Ko Min is arriving in 3 minutes" action="10:26" /><Row title="20% off Comfort rides" detail="Offer valid until 31 August" action="19 Aug" onPress={() => p.open('Promotions')} /><Row title="Payment successful" detail="Fare 5,800 MMK" action="18 Aug" /><Row title="Trip completed" detail="Thanks for riding with LaBar" action="18 Aug" /><Secondary label="Mark all as read" onPress={() => undefined} /></>;
    case 'Support': return <><Section title="How can we help?" subtitle="Search help topics or start a support case." /><SearchField label="Search help topics" /><Row title="Ride issue" detail="Driver, route, cancellation" action="Open" /><Row title="Payment issue" detail="Cash, wallet, receipt" action="Open" /><Row title="Lost item" detail="Contact support with trip context" action="Open" /><Row title="Safety concern" detail="Urgent help and follow-up" action="Open" /><Primary label="Chat with support" onPress={() => undefined} /></>;
    case 'ScheduleRide': return <><Section title="Schedule a ride" subtitle="Pick a date, time, pickup, and destination." /><Text style={styles.fieldLabel}>Pickup date and time</Text><TextInput style={styles.input} value="25 Aug 2026 · 08:30" /><Row title="Pickup" detail="Home, Sanchaung" action="Change" /><Row title="Destination" detail="Tawma Ocean, Tamwe" action="Change" /><FareCard fare={p.fare} payment={p.payment} /><Primary label="Schedule ride" onPress={() => p.open('Home')} /></>;
    case 'Promotions': return <><Section title="Promotions" subtitle="Offers are validated before payment." /><Offer title="20% off Comfort rides" detail="Maximum discount 2,000 MMK · valid until 31 Aug" /><Offer title="1,000 MMK off airport rides" detail="One use per passenger · valid until 30 Sep" /><Offer title="Invite friends" detail="Get 1,000 promo credits after their first ride" /></>;
    case 'Settings': return <><Row title="Language" detail="Myanmar and English" action="›" /><Row title="Notifications" detail="Trip, payment, promo, safety" action="›" /><Row title="Accessibility" detail="Large text and voice guidance" action="›" /><Row title="Privacy and security" detail="Passkey, devices, data controls" action="›" /><Row title="Log out" detail="End this device session" action="›" /></>;
    default: return null;
  }
}

function Section({ title, subtitle, centered = false }: { title: string; subtitle?: string; centered?: boolean }) { return <View style={centered ? styles.center : undefined}><Text style={styles.title}>{title}</Text>{subtitle && <Text style={styles.detail}>{subtitle}</Text>}</View>; }
function SearchField({ label = 'Search destination' }: { label?: string }) { return <View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><Text style={styles.searchText}>{label}</Text></View>; }
function QuickPlaces() { return <View style={styles.quick}><View><Text style={styles.cardTitle}>Home</Text><Text style={styles.small}>Sanchaung</Text></View><View><Text style={styles.cardTitle}>Work</Text><Text style={styles.small}>Sule Square</Text></View></View>; }
function MapPanel({ compact = false }: { compact?: boolean }) { return <View style={[styles.map, compact && styles.mapCompact]}><View style={styles.roadA} /><View style={styles.roadB} /><View style={styles.routeLine} /><View style={[styles.mapPin, styles.startPin]} /><View style={[styles.mapPin, styles.endPin]} /><View style={styles.car}><Text style={styles.carText}>CAR</Text></View><Text style={styles.mapLabel}>Yangon</Text></View>; }
function Row({ title, detail, action, onPress }: { title: string; detail: string; action: string; onPress?: () => void }) { return <Pressable accessibilityRole={onPress ? 'button' : undefined} onPress={onPress} style={styles.row}><View style={styles.rowIcon}><View style={styles.rowIconCore} /></View><View style={styles.grow}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.detail}>{detail}</Text></View><Text style={styles.action}>{action}</Text></Pressable>; }
function RideOption({ title, detail, price, active = false }: { title: string; detail: string; price: number; active?: boolean }) { return <View style={[styles.ride, active && styles.rideActive]}><Vehicle small /><View style={styles.grow}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.small}>{detail}</Text></View><Text style={styles.price}>{money(price)}</Text></View>; }
function Vehicle({ small = false }: { small?: boolean }) { return <View style={[styles.vehicle, small && styles.vehicleSmall]}><View style={styles.vehicleTop} /><View style={styles.vehicleBody} /><View style={styles.wheelA} /><View style={styles.wheelB} /></View>; }
function DriverCard({ large = false }: { large?: boolean }) { return <View style={[styles.driver, large && styles.driverLarge]}><View style={styles.avatar}><Text style={styles.avatarText}>KM</Text></View><View style={styles.grow}><Text style={styles.cardTitle}>Ko Min · 4.9</Text><Text style={styles.detail}>Toyota Prius · ADG-8829C</Text></View><Text style={styles.action}>Call</Text></View>; }
function PaymentRow({ method, active, onPress }: { method: PaymentMethod; active: boolean; onPress: () => void }) { const labels: Record<PaymentMethod,string> = { CASH:'Cash', KBZPAY:'KBZPay', WAVEPAY:'WavePay', AYAPAY:'AYA Pay' }; return <Pressable onPress={onPress} style={styles.paymentRow}><View style={[styles.payIcon, active && styles.payIconActive]}><Text style={styles.payIconText}>{labels[method].slice(0,1)}</Text></View><Text style={styles.cardTitle}>{labels[method]}</Text><View style={[styles.radio, active && styles.radioActive]} /></Pressable>; }
function FareCard({ fare, payment }: { fare: ReturnType<typeof calculateFare>; payment: PaymentMethod }) { return <View style={styles.fare}><Line label="Transport fare" value={money(fare.transportFareMMK)} /><Line label="LaBar service fee" value={money(fare.serviceFeeMMK)} />{fare.promoDiscountMMK > 0 && <Line label="Promo credit" value={`-${money(fare.promoDiscountMMK)}`} />}<Line label="Subtotal" value={money(fare.subtotalMMK)} />{payment === 'CASH' && <Line label="Cash rounding" value={money(fare.cashRoundingMMK)} />}<Line label="Payable" value={money(fare.payableMMK)} strong /></View>; }
function Line({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <View style={styles.line}><Text style={strong ? styles.strong : styles.detail}>{label}</Text><Text style={strong ? styles.strong : styles.cardTitle}>{value}</Text></View>; }
function StatBar({ items }: { items: string[][] }) { return <View style={styles.statBar}>{items.map(([value,label]) => <View key={label} style={styles.stat}><Text style={styles.cardTitle}>{value}</Text><Text style={styles.small}>{label}</Text></View>)}</View>; }
function Tabs({ labels }: { labels: string[] }) { return <View style={styles.tabs}>{labels.map((label,index) => <View key={label} style={[styles.tab,index === 0 && styles.tabActive]}><Text style={[styles.tabText,index === 0 && styles.tabTextActive]}>{label}</Text></View>)}</View>; }
function Offer({ title, detail }: { title: string; detail: string }) { return <View style={styles.offer}><View style={styles.offerBadge}><Text style={styles.offerBadgeText}>OFFER</Text></View><Text style={styles.offerTitle}>{title}</Text><Text style={styles.detail}>{detail}</Text><Secondary label="Use now" onPress={() => undefined} /></View>; }
function SearchRings() { return <View style={styles.rings}><View style={styles.ringThree}><View style={styles.ringTwo}><View style={styles.ringOne}><Vehicle /></View></View></View></View>; }
function Primary({ label, onPress, yellow = false }: { label: string; onPress: () => void; yellow?: boolean }) { return <Pressable accessibilityRole="button" style={[styles.primary,yellow && styles.primaryYellow]} onPress={onPress}><Text style={[styles.primaryText,yellow && styles.primaryYellowText]}>{label}</Text></Pressable>; }
function Secondary({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" style={styles.secondary} onPress={onPress}><Text style={styles.secondaryText}>{label}</Text></Pressable>; }
function BottomNav({ current, open }: { current: PassengerScreenId; open: (screen: PassengerScreenId) => void }) { const tabs: [PassengerScreenId,string][] = [['Home','Home'],['MyTrips','Trips'],['Wallet','Wallet'],['Profile','Me']]; return <View style={styles.nav}>{tabs.map(([id,label]) => <Pressable key={id} onPress={() => open(id)} style={styles.navItem}><View style={[styles.navGlyph,current === id && styles.navGlyphActive]} /><Text style={[styles.navText,current === id && styles.navActive]}>{label}</Text></Pressable>)}</View>; }

const styles = StyleSheet.create({
  safe:{flex:1,backgroundColor:'#fff'}, content:{padding:16,paddingBottom:96}, header:{height:52,paddingHorizontal:16,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#ececef'}, back:{fontSize:31,lineHeight:31,width:32}, headerTitle:{fontSize:16,fontWeight:'800',flex:1,textAlign:'center'}, notificationDot:{width:9,height:9,borderRadius:5,backgroundColor:RED},
  splash:{flex:1,alignItems:'center',justifyContent:'center',padding:28,backgroundColor:'#fff4ef'}, mark:{width:152,height:178,borderRadius:78,backgroundColor:RED,alignItems:'center',paddingTop:18}, markCore:{width:116,height:116,borderRadius:58,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'}, markCar:{fontSize:22,fontWeight:'900'}, shield:{position:'absolute',bottom:0,width:64,height:70,borderRadius:22,backgroundColor:RED,borderWidth:4,borderColor:'#fff',alignItems:'center',justifyContent:'center'}, shieldCheck:{color:'#fff',fontWeight:'900',fontSize:28}, splashBrand:{fontSize:34,fontWeight:'900',letterSpacing:2,color:RED,marginTop:24}, splashTagline:{fontSize:15,marginBottom:70}, splashPlace:{fontSize:12,fontWeight:'700',marginBottom:14},
  hero:{fontSize:27,lineHeight:33,fontWeight:'800',marginVertical:14}, red:{color:RED}, title:{fontSize:21,fontWeight:'800',letterSpacing:-.4,marginTop:5}, detail:{fontSize:12,color:'#73777d',lineHeight:18}, small:{fontSize:10,color:'#85898f',lineHeight:15}, cardTitle:{fontSize:13,fontWeight:'700'}, center:{alignItems:'center',marginVertical:10}, grow:{flex:1},
  search:{height:47,borderWidth:1,borderColor:'#e8e8eb',borderRadius:10,flexDirection:'row',alignItems:'center',paddingHorizontal:14,marginVertical:10,backgroundColor:'#fff'}, searchIcon:{fontSize:21,color:RED,marginRight:10}, searchText:{fontSize:12,color:'#8b8e93'}, quick:{flexDirection:'row',justifyContent:'space-around',marginBottom:9},
  map:{height:258,marginHorizontal:-16,marginTop:-16,marginBottom:12,overflow:'hidden',backgroundColor:'#eef0ec'}, mapCompact:{height:186,marginTop:5,marginHorizontal:0,borderRadius:11}, roadA:{position:'absolute',width:450,height:10,backgroundColor:'#fff',top:90,left:-35,transform:[{rotate:'25deg'}]}, roadB:{position:'absolute',width:390,height:7,backgroundColor:'#dce7ed',top:145,left:-10,transform:[{rotate:'-30deg'}]}, routeLine:{position:'absolute',width:185,height:5,backgroundColor:RED,top:122,left:92,transform:[{rotate:'-26deg'}]}, mapPin:{position:'absolute',width:16,height:16,borderRadius:8,backgroundColor:YELLOW,borderWidth:3,borderColor:'#fff'}, startPin:{left:72,top:158}, endPin:{right:72,top:69,backgroundColor:RED}, car:{position:'absolute',left:172,top:112,width:42,height:23,borderRadius:9,backgroundColor:'#171717',alignItems:'center',justifyContent:'center'}, carText:{color:'#fff',fontSize:7,fontWeight:'800'}, mapLabel:{position:'absolute',top:138,left:143,fontSize:11,fontWeight:'700',color:'#787d80'},
  row:{minHeight:62,borderWidth:1,borderColor:'#ececef',borderRadius:10,padding:10,marginVertical:5,flexDirection:'row',alignItems:'center',gap:9,backgroundColor:'#fff'}, rowIcon:{width:30,height:30,borderRadius:15,backgroundColor:'#fff1f1',alignItems:'center',justifyContent:'center'}, rowIconCore:{width:9,height:9,borderRadius:5,backgroundColor:RED}, action:{fontSize:10,fontWeight:'700',color:RED,maxWidth:88,textAlign:'right'},
  input:{borderWidth:1,borderColor:'#dfe1e4',borderRadius:8,padding:11,marginVertical:9,color:'#171717'}, fieldLabel:{fontSize:11,color:'#73777d',marginTop:13}, primary:{minHeight:45,borderRadius:23,backgroundColor:RED,alignItems:'center',justifyContent:'center',paddingHorizontal:18,marginTop:11}, primaryText:{fontSize:12,fontWeight:'800',color:'#fff'}, primaryYellow:{backgroundColor:YELLOW}, primaryYellowText:{color:'#171717'}, secondary:{minHeight:43,borderWidth:1,borderColor:'#e4e4e7',borderRadius:22,alignItems:'center',justifyContent:'center',marginTop:9}, secondaryText:{fontSize:12,fontWeight:'700'},
  ride:{minHeight:77,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:'#ededf0',paddingVertical:8,paddingHorizontal:6}, rideActive:{borderWidth:1,borderColor:RED,borderRadius:10,paddingHorizontal:9,backgroundColor:'#fffafa'}, price:{fontSize:11,fontWeight:'800'}, vehicle:{width:96,height:54,position:'relative',marginHorizontal:6}, vehicleSmall:{width:70,height:44}, vehicleTop:{position:'absolute',width:'55%',height:'45%',left:'22%',top:'12%',borderRadius:12,backgroundColor:'#bfc3c7'}, vehicleBody:{position:'absolute',width:'92%',height:'34%',left:'4%',top:'42%',borderRadius:9,backgroundColor:'#222'}, wheelA:{position:'absolute',width:14,height:14,borderRadius:7,backgroundColor:'#111',bottom:3,left:14}, wheelB:{position:'absolute',width:14,height:14,borderRadius:7,backgroundColor:'#111',bottom:3,right:14},
  paymentRow:{height:57,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:'#ededf0'}, payIcon:{width:29,height:29,borderRadius:7,backgroundColor:'#eef0f3',alignItems:'center',justifyContent:'center'}, payIconActive:{backgroundColor:YELLOW}, payIconText:{fontWeight:'900'}, radio:{marginLeft:'auto',width:16,height:16,borderRadius:8,borderWidth:2,borderColor:'#d2d4d7'}, radioActive:{borderColor:RED,backgroundColor:RED}, fare:{borderWidth:1,borderColor:'#e8e8eb',borderRadius:10,paddingHorizontal:12,marginTop:10}, line:{minHeight:38,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#ededf0'}, strong:{fontSize:14,fontWeight:'800'},
  statBar:{flexDirection:'row',borderWidth:1,borderColor:'#ececef',borderRadius:10,marginVertical:9}, stat:{flex:1,alignItems:'center',paddingVertical:10}, tabs:{flexDirection:'row',padding:3,borderRadius:9,backgroundColor:'#f2f2f3',marginVertical:10}, tab:{flex:1,alignItems:'center',paddingVertical:7,borderRadius:7}, tabActive:{backgroundColor:RED}, tabText:{fontSize:10,color:'#70747a'}, tabTextActive:{color:'#fff',fontWeight:'800'},
  driver:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'#ececef',borderRadius:11,padding:11,marginVertical:9}, driverLarge:{paddingVertical:17}, avatar:{width:45,height:45,borderRadius:23,backgroundColor:'#f3d0b4',alignItems:'center',justifyContent:'center'}, avatarText:{fontSize:12,fontWeight:'900'}, plate:{alignSelf:'center',borderWidth:2,borderColor:'#222',borderRadius:4,paddingHorizontal:17,paddingVertical:6}, plateText:{fontWeight:'900',fontSize:13}, eta:{position:'absolute',zIndex:2,top:15,left:15,backgroundColor:'#fff',borderRadius:10,padding:9}, etaBig:{fontWeight:'900',fontSize:18},
  rings:{height:300,alignItems:'center',justifyContent:'center'}, ringThree:{width:280,height:280,borderRadius:140,borderWidth:1,borderColor:'#f7c5c8',alignItems:'center',justifyContent:'center'}, ringTwo:{width:208,height:208,borderRadius:104,borderWidth:1,borderColor:'#f39da2',alignItems:'center',justifyContent:'center'}, ringOne:{width:136,height:136,borderRadius:68,borderWidth:1,borderColor:RED,alignItems:'center',justifyContent:'center'}, success:{alignItems:'center',paddingVertical:15}, successCheck:{width:54,height:54,borderRadius:27,backgroundColor:GREEN,color:'#fff',fontSize:30,textAlign:'center',lineHeight:54,fontWeight:'900'}, alert:{borderWidth:1,borderColor:'#ffc7ca',backgroundColor:'#fff6f6',borderRadius:10,padding:12,marginTop:9},
  wallet:{backgroundColor:RED,borderRadius:12,padding:19,marginBottom:13}, walletLabel:{fontSize:11,color:'#fff'}, walletBalance:{fontSize:27,fontWeight:'900',color:'#fff',marginVertical:3}, profile:{alignItems:'center',paddingVertical:17}, guardian:{width:128,height:142,borderRadius:40,backgroundColor:RED,borderWidth:8,borderColor:YELLOW,alignSelf:'center',alignItems:'center',justifyContent:'center',marginTop:9}, guardianShield:{fontSize:48,color:'#fff',fontWeight:'900'}, offer:{borderWidth:1,borderColor:'#ececef',borderRadius:11,padding:13,marginVertical:7}, offerBadge:{alignSelf:'flex-start',backgroundColor:'#fff2f2',paddingHorizontal:8,paddingVertical:4,borderRadius:5}, offerBadgeText:{fontSize:8,fontWeight:'900',color:RED}, offerTitle:{fontSize:16,fontWeight:'800',marginVertical:8},
  nav:{height:62,borderTopWidth:1,borderTopColor:'#ececef',flexDirection:'row',justifyContent:'space-around',alignItems:'center',backgroundColor:'#fff'}, navItem:{width:58,alignItems:'center'}, navGlyph:{width:17,height:17,borderWidth:2,borderColor:'#85898f',borderRadius:5,marginBottom:3}, navGlyphActive:{borderColor:RED,backgroundColor:'#fff1f1'}, navText:{fontSize:9,color:'#777b82'}, navActive:{color:RED,fontWeight:'800'},
});
