CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), phone text UNIQUE, email text UNIQUE,
    display_name text NOT NULL DEFAULT '', locale text NOT NULL DEFAULT 'my-MM',
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','deleted')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), last_login_at timestamptz
);
CREATE INDEX users_phone_idx ON users(phone) WHERE phone IS NOT NULL;
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL);
CREATE TABLE permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL);
CREATE TABLE user_roles (user_id uuid REFERENCES users(id) ON DELETE CASCADE, role_id uuid REFERENCES roles(id) ON DELETE CASCADE, granted_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,role_id));
CREATE TABLE role_permissions (role_id uuid REFERENCES roles(id) ON DELETE CASCADE, permission_id uuid REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id,permission_id));
CREATE TABLE otp_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), phone text NOT NULL, purpose text NOT NULL, code_hash bytea NOT NULL, attempts smallint NOT NULL DEFAULT 0, max_attempts smallint NOT NULL DEFAULT 5, expires_at timestamptz NOT NULL, consumed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX otp_challenges_phone_idx ON otp_challenges(phone,created_at DESC);
CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), refresh_token_hash bytea UNIQUE NOT NULL, device_name text NOT NULL DEFAULT '', ip_hash bytea, user_agent_hash bytea, expires_at timestamptz NOT NULL, last_activity_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, replaced_by uuid REFERENCES sessions(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sessions_user_active_idx ON sessions(user_id,expires_at) WHERE revoked_at IS NULL;
CREATE TABLE security_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), event_type text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE devices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform text NOT NULL CHECK(platform IN ('ios','android','web')), device_id text NOT NULL,
    push_token text, push_provider text, app_type text NOT NULL CHECK(app_type IN ('passenger','driver','driverreg','admin')),
    app_version text NOT NULL DEFAULT '', os_version text NOT NULL DEFAULT '', locale text NOT NULL DEFAULT '', timezone text NOT NULL DEFAULT '',
    last_seen_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,device_id,app_type)
);
CREATE UNIQUE INDEX devices_push_token_idx ON devices(push_token) WHERE push_token IS NOT NULL;
CREATE TABLE live_activity_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), ride_id uuid, device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE, activity_type text NOT NULL, push_token text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL);

CREATE TABLE cities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, name text NOT NULL, timezone text NOT NULL, currency text NOT NULL DEFAULT 'MMK', boundary geography(MultiPolygon,4326), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE service_zones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid NOT NULL REFERENCES cities(id), name text NOT NULL, services text[] NOT NULL DEFAULT '{}', boundary geography(MultiPolygon,4326) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX service_zones_boundary_gix ON service_zones USING gist(boundary);
CREATE TABLE passenger_profiles (user_id uuid PRIMARY KEY REFERENCES users(id), photo_url text, default_payment_method text, emergency_contact_enabled boolean NOT NULL DEFAULT false, rating numeric(3,2) NOT NULL DEFAULT 5, completed_trip_count integer NOT NULL DEFAULT 0);
CREATE TABLE saved_places (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), type text NOT NULL CHECK(type IN ('home','work','custom')), name text NOT NULL, address text NOT NULL, location geography(Point,4326) NOT NULL, pickup_note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX saved_places_user_idx ON saved_places(user_id,created_at DESC);

CREATE TABLE driver_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','under_review','documents_requested','verification','approved','rejected','withdrawn')), legal_name text NOT NULL DEFAULT '', date_of_birth date, nrc_ciphertext bytea, address_ciphertext bytea, submitted_at timestamptz, reviewed_by uuid REFERENCES users(id), reviewed_at timestamptz, decision_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX driver_applications_user_idx ON driver_applications(user_id);
CREATE INDEX driver_applications_status_idx ON driver_applications(status,created_at);
CREATE TABLE driver_application_steps (application_id uuid REFERENCES driver_applications(id) ON DELETE CASCADE, step text NOT NULL, data jsonb NOT NULL DEFAULT '{}', completed_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(application_id,step));
CREATE TABLE uploads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL REFERENCES users(id), object_key text UNIQUE NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes > 0), checksum_sha256 text NOT NULL, document_type text NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','uploaded','rejected')), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE driver_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES driver_applications(id) ON DELETE CASCADE, upload_id uuid NOT NULL REFERENCES uploads(id), type text NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','verified','rejected','expired')), expires_on date, rejection_reason text, verified_by uuid REFERENCES users(id), verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE driver_verifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES driver_applications(id), type text NOT NULL, provider text NOT NULL, result text NOT NULL, confidence numeric(5,4), evidence_upload_id uuid REFERENCES uploads(id), reviewed_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE application_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES driver_applications(id), author_id uuid NOT NULL REFERENCES users(id), note text NOT NULL, visibility text NOT NULL DEFAULT 'internal', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE drivers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE NOT NULL REFERENCES users(id), driver_number text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','suspended','inactive')), availability text NOT NULL DEFAULT 'offline' CHECK(availability IN ('offline','available','offered','enroute_pickup','waiting_passenger','on_trip','paused')), rating numeric(3,2) NOT NULL DEFAULT 5, completed_rides integer NOT NULL DEFAULT 0, acceptance_rate numeric(5,4) NOT NULL DEFAULT 0, cancellation_rate numeric(5,4) NOT NULL DEFAULT 0, approved_at timestamptz, last_heartbeat_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX drivers_status_idx ON drivers(status,availability);
CREATE TABLE vehicles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), driver_id uuid NOT NULL REFERENCES drivers(id), type text NOT NULL, make text NOT NULL, model text NOT NULL, year smallint NOT NULL, color text NOT NULL, plate text UNIQUE NOT NULL, capacity smallint NOT NULL CHECK(capacity > 0), services text[] NOT NULL DEFAULT '{ride}', status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','suspended','inactive')), active boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX vehicles_driver_active_idx ON vehicles(driver_id) WHERE active;

CREATE TABLE ride_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, name text NOT NULL, capacity smallint NOT NULL, service text NOT NULL DEFAULT 'ride', active boolean NOT NULL DEFAULT true, display_order smallint NOT NULL DEFAULT 0);
CREATE TABLE fare_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid NOT NULL REFERENCES cities(id), version integer NOT NULL, status text NOT NULL CHECK(status IN ('draft','active','retired')), effective_from timestamptz NOT NULL, effective_to timestamptz, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(city_id,version));
CREATE UNIQUE INDEX fare_versions_city_active_idx ON fare_versions(city_id) WHERE status='active';
CREATE TABLE fare_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fare_version_id uuid NOT NULL REFERENCES fare_versions(id), ride_type_id uuid NOT NULL REFERENCES ride_types(id), base_fare_mmk bigint NOT NULL, included_distance_meters integer NOT NULL, per_km_mmk bigint NOT NULL, low_speed_threshold_kph numeric(5,2) NOT NULL DEFAULT 10, low_speed_per_minute_mmk bigint NOT NULL DEFAULT 0, minimum_fare_mmk bigint NOT NULL, booking_fee_mmk bigint NOT NULL DEFAULT 0, service_fee_mmk bigint NOT NULL DEFAULT 0, airport_surcharge_mmk bigint NOT NULL DEFAULT 0, night_surcharge_mmk bigint NOT NULL DEFAULT 0, multiplier numeric(6,3) NOT NULL DEFAULT 1, cash_rounding_unit_mmk bigint NOT NULL DEFAULT 100, driver_commission_bps integer NOT NULL DEFAULT 1500 CHECK(driver_commission_bps BETWEEN 0 AND 10000), UNIQUE(fare_version_id,ride_type_id));
CREATE TABLE fare_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fare_plan_id uuid NOT NULL REFERENCES fare_plans(id) ON DELETE CASCADE, rule_type text NOT NULL, priority smallint NOT NULL DEFAULT 0, conditions jsonb NOT NULL DEFAULT '{}', adjustment jsonb NOT NULL DEFAULT '{}');
CREATE TABLE promotions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, status text NOT NULL CHECK(status IN ('draft','active','retired')), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, city_id uuid REFERENCES cities(id), service text, ride_type_id uuid REFERENCES ride_types(id), minimum_fare_mmk bigint NOT NULL DEFAULT 0, new_user_only boolean NOT NULL DEFAULT false, max_redemptions integer, per_user_limit integer NOT NULL DEFAULT 1, discount_percent numeric(5,2), discount_fixed_mmk bigint, maximum_discount_mmk bigint, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE promo_codes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), promotion_id uuid NOT NULL REFERENCES promotions(id), code text UNIQUE NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE fare_quotes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), passenger_id uuid REFERENCES users(id), city_id uuid NOT NULL REFERENCES cities(id), pricing_version_id uuid NOT NULL REFERENCES fare_versions(id), pickup geography(Point,4326) NOT NULL, destination geography(Point,4326) NOT NULL, distance_meters integer NOT NULL, duration_seconds integer NOT NULL, route_geometry text, scheduled_at timestamptz, promo_code_id uuid REFERENCES promo_codes(id), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE fare_quote_options (quote_id uuid REFERENCES fare_quotes(id) ON DELETE CASCADE, ride_type_id uuid REFERENCES ride_types(id), estimated_arrival_seconds integer, transport_fare_mmk bigint NOT NULL, low_speed_fare_mmk bigint NOT NULL DEFAULT 0, booking_fee_mmk bigint NOT NULL DEFAULT 0, service_fee_mmk bigint NOT NULL DEFAULT 0, surcharge_mmk bigint NOT NULL DEFAULT 0, discount_mmk bigint NOT NULL DEFAULT 0, total_mmk bigint NOT NULL, currency text NOT NULL DEFAULT 'MMK', breakdown jsonb NOT NULL, PRIMARY KEY(quote_id,ride_type_id));
CREATE TABLE promo_redemptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), promotion_id uuid NOT NULL REFERENCES promotions(id), promo_code_id uuid REFERENCES promo_codes(id), user_id uuid NOT NULL REFERENCES users(id), quote_id uuid REFERENCES fare_quotes(id), ride_id uuid, discount_mmk bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE rides (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), passenger_id uuid NOT NULL REFERENCES users(id), driver_id uuid REFERENCES drivers(id), vehicle_id uuid REFERENCES vehicles(id), quote_id uuid NOT NULL REFERENCES fare_quotes(id), ride_type_id uuid NOT NULL REFERENCES ride_types(id), city_id uuid NOT NULL REFERENCES cities(id), pricing_version_id uuid NOT NULL REFERENCES fare_versions(id), status text NOT NULL CHECK(status IN ('requested','searching','driver_offered','driver_assigned','driver_enroute','driver_arrived','pickup_confirmed','in_progress','completed','passenger_cancelled','driver_cancelled','system_cancelled','no_driver_found')), pickup geography(Point,4326) NOT NULL, destination geography(Point,4326) NOT NULL, pickup_address text NOT NULL DEFAULT '', destination_address text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', payment_method text NOT NULL, pickup_pin_hash bytea, pickup_pin_ciphertext bytea, trip_distance_meters integer NOT NULL DEFAULT 0, trip_duration_seconds integer NOT NULL DEFAULT 0, low_speed_seconds integer NOT NULL DEFAULT 0, estimated_total_mmk bigint NOT NULL, final_total_mmk bigint, requested_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, completed_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 1);
CREATE INDEX rides_passenger_idx ON rides(passenger_id,requested_at DESC);
CREATE INDEX rides_driver_idx ON rides(driver_id,requested_at DESC) WHERE driver_id IS NOT NULL;
CREATE INDEX rides_active_idx ON rides(status,requested_at) WHERE status IN ('requested','searching','driver_offered','driver_assigned','driver_enroute','driver_arrived','pickup_confirmed','in_progress');
ALTER TABLE live_activity_sessions ADD CONSTRAINT live_activity_ride_fk FOREIGN KEY(ride_id) REFERENCES rides(id) ON DELETE CASCADE;
ALTER TABLE promo_redemptions ADD CONSTRAINT promo_redemption_ride_fk FOREIGN KEY(ride_id) REFERENCES rides(id);
CREATE TABLE ride_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ride_id uuid NOT NULL REFERENCES rides(id) ON DELETE CASCADE, sequence bigint NOT NULL, event_type text NOT NULL, actor_type text NOT NULL, actor_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(ride_id,sequence));
CREATE INDEX ride_events_ride_idx ON ride_events(ride_id,sequence);
CREATE TABLE ride_ratings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ride_id uuid NOT NULL REFERENCES rides(id), rater_user_id uuid NOT NULL REFERENCES users(id), rated_user_id uuid NOT NULL REFERENCES users(id), stars smallint NOT NULL CHECK(stars BETWEEN 1 AND 5), tags text[] NOT NULL DEFAULT '{}', comment text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(ride_id,rater_user_id));
CREATE TABLE ride_offers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ride_id uuid NOT NULL REFERENCES rides(id), driver_id uuid NOT NULL REFERENCES drivers(id), offered_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','rejected','expired','cancelled')), UNIQUE(ride_id,driver_id));
CREATE UNIQUE INDEX ride_offers_driver_pending_idx ON ride_offers(driver_id) WHERE status='pending';
CREATE TABLE trip_location_samples (id bigserial PRIMARY KEY, ride_id uuid NOT NULL REFERENCES rides(id) ON DELETE CASCADE, driver_id uuid NOT NULL REFERENCES drivers(id), location geography(Point,4326) NOT NULL, heading numeric(6,2), speed_kph numeric(7,2), accuracy_meters numeric(7,2), client_timestamp timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), risk_flags text[] NOT NULL DEFAULT '{}');
CREATE INDEX trip_location_ride_idx ON trip_location_samples(ride_id,created_at DESC);
CREATE TABLE risk_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), driver_id uuid REFERENCES drivers(id), ride_id uuid REFERENCES rides(id), type text NOT NULL, severity text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', reviewed_at timestamptz, reviewed_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE payment_methods (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), type text NOT NULL, provider text NOT NULL, provider_reference text, status text NOT NULL DEFAULT 'active', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ride_id uuid REFERENCES rides(id), user_id uuid NOT NULL REFERENCES users(id), method text NOT NULL, provider text NOT NULL, amount_mmk bigint NOT NULL, status text NOT NULL CHECK(status IN ('pending','authorized','cash_due','paid','failed','cancelled','refunded','partially_refunded')), provider_reference text, idempotency_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX payments_idempotency_idx ON payments(user_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE TABLE payment_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), payment_id uuid NOT NULL REFERENCES payments(id), request jsonb NOT NULL DEFAULT '{}', response jsonb NOT NULL DEFAULT '{}', status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE wallets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE NOT NULL REFERENCES users(id), currency text NOT NULL DEFAULT 'MMK', cached_balance_mmk bigint NOT NULL DEFAULT 0, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE wallet_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), wallet_id uuid NOT NULL REFERENCES wallets(id), type text NOT NULL CHECK(type IN ('credit','debit','refund','promotion','adjustment','ride_payment','topup')), amount_mmk bigint NOT NULL CHECK(amount_mmk > 0), direction smallint NOT NULL CHECK(direction IN (-1,1)), reference_type text NOT NULL, reference_id uuid, idempotency_key text NOT NULL, balance_after_mmk bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(wallet_id,idempotency_key));
CREATE INDEX wallet_transactions_history_idx ON wallet_transactions(wallet_id,created_at DESC);
CREATE TABLE driver_earnings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), driver_id uuid NOT NULL REFERENCES drivers(id), ride_id uuid UNIQUE REFERENCES rides(id), gross_mmk bigint NOT NULL, commission_mmk bigint NOT NULL, net_mmk bigint NOT NULL, pricing_version_id uuid NOT NULL REFERENCES fare_versions(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE driver_adjustments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), driver_id uuid NOT NULL REFERENCES drivers(id), amount_mmk bigint NOT NULL, reason text NOT NULL, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE driver_payouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), driver_id uuid NOT NULL REFERENCES drivers(id), amount_mmk bigint NOT NULL, status text NOT NULL, provider text NOT NULL, provider_reference text, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), category text NOT NULL, title text NOT NULL, body text NOT NULL, data jsonb NOT NULL DEFAULT '{}', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX notifications_user_idx ON notifications(user_id,created_at DESC);
CREATE TABLE notification_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), notification_id uuid NOT NULL REFERENCES notifications(id), device_id uuid REFERENCES devices(id), channel text NOT NULL CHECK(channel IN ('push','email','sms','in_app','live_activity')), provider text, status text NOT NULL DEFAULT 'pending', attempts smallint NOT NULL DEFAULT 0, provider_reference text, last_error text, next_attempt_at timestamptz NOT NULL DEFAULT now(), delivered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX notification_delivery_jobs_idx ON notification_deliveries(status,next_attempt_at);
CREATE FUNCTION create_notification_deliveries() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO notification_deliveries(notification_id,device_id,channel,provider) SELECT NEW.id,d.id,'push',d.push_provider FROM devices d WHERE d.user_id=NEW.user_id AND d.push_token IS NOT NULL; INSERT INTO notification_deliveries(notification_id,channel,status,delivered_at) VALUES(NEW.id,'in_app','delivered',now()); RETURN NEW; END $$;
CREATE TRIGGER notifications_delivery_trigger AFTER INSERT ON notifications FOR EACH ROW EXECUTE FUNCTION create_notification_deliveries();
CREATE TABLE jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), type text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','completed','failed')), attempts smallint NOT NULL DEFAULT 0, max_attempts smallint NOT NULL DEFAULT 10, run_at timestamptz NOT NULL DEFAULT now(), locked_at timestamptz, locked_by text, last_error text, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE INDEX jobs_ready_idx ON jobs(run_at,created_at) WHERE status='pending';

CREATE TABLE trusted_contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, phone_ciphertext bytea NOT NULL, verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE trip_shares (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ride_id uuid NOT NULL REFERENCES rides(id), created_by uuid NOT NULL REFERENCES users(id), token_hash bytea UNIQUE NOT NULL, location_precision text NOT NULL DEFAULT 'approximate', expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE safety_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ride_id uuid REFERENCES rides(id), user_id uuid NOT NULL REFERENCES users(id), type text NOT NULL, status text NOT NULL DEFAULT 'open', location geography(Point,4326), device_id uuid REFERENCES devices(id), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, resolved_by uuid REFERENCES users(id));
CREATE TABLE safety_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), safety_event_id uuid REFERENCES safety_events(id), reporter_id uuid NOT NULL REFERENCES users(id), details text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE support_tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), ride_id uuid REFERENCES rides(id), type text NOT NULL, status text NOT NULL DEFAULT 'new' CHECK(status IN ('new','open','waiting','escalated','resolved','closed')), priority text NOT NULL DEFAULT 'normal' CHECK(priority IN ('low','normal','high','urgent')), subject text NOT NULL, description text NOT NULL, contact_ciphertext bytea, assigned_to uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX support_tickets_queue_idx ON support_tickets(status,priority,created_at);
CREATE TABLE support_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES users(id), body text NOT NULL, internal boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE support_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES support_tickets(id), assignee_id uuid NOT NULL REFERENCES users(id), assigned_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE content_pages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, title text NOT NULL, body jsonb NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','unpublished')), published_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE help_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, name text NOT NULL, status text NOT NULL DEFAULT 'published', display_order integer NOT NULL DEFAULT 0);
CREATE TABLE help_articles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), category_id uuid NOT NULL REFERENCES help_categories(id), slug text UNIQUE NOT NULL, title text NOT NULL, body jsonb NOT NULL, status text NOT NULL DEFAULT 'draft', published_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE faq_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), question text NOT NULL, answer jsonb NOT NULL, status text NOT NULL DEFAULT 'draft', display_order integer NOT NULL DEFAULT 0);
CREATE TABLE deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sender_id uuid NOT NULL REFERENCES users(id), receiver jsonb NOT NULL, pickup geography(Point,4326) NOT NULL, destination geography(Point,4326) NOT NULL, package jsonb NOT NULL, driver_id uuid REFERENCES drivers(id), status text NOT NULL CHECK(status IN ('quoted','requested','searching','assigned','picked_up','in_transit','delivered','cancelled')), price_mmk bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE business_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, status text NOT NULL DEFAULT 'active', billing_profile jsonb NOT NULL DEFAULT '{}', spending_policy jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE business_members (business_id uuid REFERENCES business_accounts(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), role text NOT NULL, cost_center text, PRIMARY KEY(business_id,user_id));
CREATE TABLE business_rides (business_id uuid REFERENCES business_accounts(id), ride_id uuid REFERENCES rides(id), member_id uuid REFERENCES users(id), cost_center text, PRIMARY KEY(business_id,ride_id));
CREATE TABLE scheduled_rides (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), passenger_id uuid NOT NULL REFERENCES users(id), quote_id uuid NOT NULL REFERENCES fare_quotes(id), scheduled_at timestamptz NOT NULL, dispatch_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'scheduled', activated_ride_id uuid REFERENCES rides(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX scheduled_rides_activation_idx ON scheduled_rides(dispatch_at) WHERE status='scheduled';
CREATE TABLE airports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid NOT NULL REFERENCES cities(id), code text UNIQUE NOT NULL, name text NOT NULL, zone geography(Polygon,4326), pickup_instructions jsonb NOT NULL DEFAULT '{}', active boolean NOT NULL DEFAULT true);
CREATE TABLE feature_flags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL, scope text NOT NULL, scope_value text NOT NULL DEFAULT '', enabled boolean NOT NULL, config jsonb NOT NULL DEFAULT '{}', minimum_version text, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(key,scope,scope_value));
CREATE TABLE app_versions (app text NOT NULL, platform text NOT NULL, minimum_version text NOT NULL, latest_version text NOT NULL, force_update boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(app,platform));
CREATE TABLE maintenance_modes (scope text PRIMARY KEY, enabled boolean NOT NULL DEFAULT false, message text NOT NULL DEFAULT '', starts_at timestamptz, ends_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency_keys (scope text NOT NULL, actor_id uuid NOT NULL, key text NOT NULL, request_hash bytea NOT NULL, response_status integer, response_body jsonb, locked_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, PRIMARY KEY(scope,actor_id,key));
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES users(id), actor_type text NOT NULL, action text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, before_data jsonb, after_data jsonb, ip_hash bytea, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_logs_resource_idx ON audit_logs(resource_type,resource_id,created_at DESC);
CREATE TABLE analytics_events (id bigserial PRIMARY KEY, event_type text NOT NULL, actor_kind text, city_id uuid REFERENCES cities(id), ride_id uuid REFERENCES rides(id), properties jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

INSERT INTO roles(name) VALUES ('passenger'),('driver'),('driver_applicant'),('support_agent'),('dispatcher'),('admin'),('super_admin'),('operations_manager'),('driver_verifier'),('finance'),('content_manager'),('analyst');
INSERT INTO permissions(name) VALUES ('ride.read'),('ride.cancel'),('ride.reassign'),('driver.approve'),('payment.refund'),('promo.create'),('support.manage'),('content.publish'),('safety.read'),('operations.map'),('audit.read'),('pricing.manage');
INSERT INTO ride_types(code,name,capacity,service,display_order) VALUES ('standard','Standard',4,'ride',1),('comfort','Comfort',4,'ride',2),('premium','Premium',4,'ride',3),('xl','XL',6,'ride',4),('ev','EV',4,'ride',5);
INSERT INTO cities(slug,name,timezone,currency,active) VALUES ('yangon','Yangon','Asia/Yangon','MMK',true);
WITH c AS (SELECT id FROM cities WHERE slug='yangon'), v AS (
  INSERT INTO fare_versions(city_id,version,status,effective_from) SELECT id,1,'active',now() FROM c RETURNING id
)
INSERT INTO fare_plans(fare_version_id,ride_type_id,base_fare_mmk,included_distance_meters,per_km_mmk,low_speed_threshold_kph,low_speed_per_minute_mmk,minimum_fare_mmk,cash_rounding_unit_mmk,multiplier)
SELECT v.id,rt.id,5000,3000,1500,10,150,5000,100,CASE rt.code WHEN 'comfort' THEN 1.25 WHEN 'premium' THEN 1.7 WHEN 'xl' THEN 1.9 WHEN 'ev' THEN 1.05 ELSE 1 END FROM v CROSS JOIN ride_types rt;
