import React,{useMemo,useState} from 'react';
import {Linking,StyleSheet,Text,View} from 'react-native';
import {Controller,useForm} from 'react-hook-form';
import {z} from 'zod';
import {zodResolver} from '@hookform/resolvers/zod';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {differenceInYears,parseISO} from 'date-fns';
import {Screen} from '../../components/layout/Screen';
import {ErrorSummary,PrimaryButton,TextField} from '../../components/forms/Fields';
import {StepRow} from '../../components/status/StepRow';
import {colors} from '../../design-system/colors';
import {driverRegService} from '../../services/driverReg.service';
import {useRegistrationCase} from '../../app/providers/RegistrationCaseProvider';
import type {RootParams} from '../../app/navigation/types';
import type {StepKey} from '../../types/api';
import {environment} from '../../lib/config/environment';

const steps:Array<{key:StepKey;label:string;icon:Parameters<typeof StepRow>[0]['icon']}>= [{key:'personal',label:'Personal information',icon:'identity'},{key:'nrc',label:'NRC details',icon:'nrc'},{key:'driving_licence',label:'Driving licence',icon:'licence'},{key:'face_liveness',label:'Face and liveness',icon:'face'},{key:'vehicle',label:'Vehicle information',icon:'vehicle'},{key:'vehicle_documents',label:'Vehicle documents',icon:'document'},{key:'payout',label:'Payout information',icon:'review'},{key:'agreement',label:'Agreement',icon:'approval'}];

export function ApplicationHome({navigation}:NativeStackScreenProps<RootParams,'Home'>){
  const{caseId,clearCase}=useRegistrationCase();const query=useQuery({queryKey:['application',caseId],queryFn:()=>driverRegService.application(caseId!),enabled:!!caseId});
  if(query.isLoading)return <Screen title="Restoring application"><Text style={s.muted}>Loading the authoritative application state…</Text></Screen>;
  if(query.error)return <Screen title="Application unavailable"><ErrorSummary message={query.error.message}/><PrimaryButton label="Retry" onPress={()=>query.refetch()}/></Screen>;
  const app=query.data!;const editable=app.status==='draft'||app.status==='documents_requested';
  return <Screen title="Application progress" eyebrow={app.status.replaceAll('_',' ')}><Text style={s.lead}>Registration staff are the recorded actor. The prospective driver remains the separate applicant.</Text><View style={s.progress}><Text style={s.progressValue}>{Object.keys(app.steps||{}).length}</Text><Text style={s.muted}>saved sections from the API</Text></View>{steps.map(item=><StepRow key={item.key} label={item.label} icon={item.icon} state={app.requested_corrections?.some(c=>c.step===item.key)?'correction':app.steps?.[item.key]?'complete':'pending'}/>)}<View style={s.space}/>{editable?<PrimaryButton label="Continue application" onPress={()=>navigation.navigate('Personal')}/>:<PrimaryButton label="View current status" tone="yellow" onPress={()=>navigation.navigate('Status')}/>}<View style={s.space}/><PrimaryButton label="Return to assigned cases" tone="yellow" onPress={clearCase}/></Screen>;
}

const personalSchema=z.object({legal_name_en:z.string().min(2,'Enter the legal English name.'),legal_name_my:z.string().optional(),preferred_display_name:z.string().min(2),date_of_birth:z.string().regex(/^\d{4}-\d{2}-\d{2}$/,'Use YYYY-MM-DD.'),email:z.string().email().or(z.literal('')),current_address:z.string().min(5),city:z.string().min(2),township:z.string().min(2),emergency_contact_name:z.string().min(2),emergency_contact_relationship:z.string().min(2),emergency_contact_phone:z.string().regex(/^09\d{7,9}$/)});type Personal=z.infer<typeof personalSchema>;
export function PersonalScreen({navigation}:NativeStackScreenProps<RootParams,'Personal'>){
  const{caseId}=useRegistrationCase();const client=useQueryClient();const form=useForm<Personal>({resolver:zodResolver(personalSchema),defaultValues:{legal_name_en:'',legal_name_my:'',preferred_display_name:'',date_of_birth:'',email:'',current_address:'',city:'Yangon',township:'',emergency_contact_name:'',emergency_contact_relationship:'',emergency_contact_phone:''}});
  const mutation=useMutation({mutationFn:(data:Personal)=>driverRegService.saveStep(caseId!,'personal',{...data,legal_name:data.legal_name_en},true),onSuccess:async()=>{await client.invalidateQueries({queryKey:['application',caseId]});navigation.navigate('Requirements',{kind:'identity'});}});
  const dob=form.watch('date_of_birth');const age=useMemo(()=>{try{return /^\d{4}-/.test(dob)?differenceInYears(new Date(),parseISO(dob)):null;}catch{return null}},[dob]);
  return <Screen title="Personal information" eyebrow="Step 1" footer={<PrimaryButton label={mutation.isPending?'Saving securely…':'Save & Continue'} disabled={mutation.isPending} onPress={form.handleSubmit(data=>mutation.mutate(data))}/>}><ErrorSummary message={mutation.error?.message}/>{(['legal_name_en','legal_name_my','preferred_display_name','date_of_birth','email','current_address','city','township','emergency_contact_name','emergency_contact_relationship','emergency_contact_phone'] as const).map(name=><Controller key={name} control={form.control} name={name} render={({field,fieldState})=><TextField label={name.replaceAll('_',' ')} value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} error={fieldState.error?.message} keyboardType={name.includes('phone')?'phone-pad':name==='email'?'email-address':'default'} autoCapitalize={name==='email'?'none':'sentences'}/>}/>)}{age!==null?<Text style={s.age}>Derived age: {age}. Eligibility is validated by the API.</Text>:null}</Screen>;
}

export function RequirementsScreen({route,navigation}:NativeStackScreenProps<RootParams,'Requirements'>){const query=useQuery({queryKey:['config'],queryFn:driverRegService.config});const kind=route.params.kind;const capability=kind==='ocr'?query.data?.driverreg?.ocr_enabled&&environment.localCapabilities.ocr:kind==='liveness'?query.data?.driverreg?.liveness_enabled&&environment.localCapabilities.liveness:true;return <Screen title={kind==='identity'?'Identity and document requirements':kind==='ocr'?'Licence OCR':kind==='liveness'?'Face and liveness':'Registration requirement'} eyebrow="Backend controlled"><Text style={s.lead}>{capability?'This capability is enabled by mobile configuration and the application build. Continue to the API-backed workflow.':'This capability is unavailable because the required backend contract or configured provider is not enabled. DriverReg will not simulate a successful result.'}</Text><PrimaryButton label="Return to application" onPress={()=>navigation.navigate('Home')}/></Screen>}

export function ReviewScreen({navigation}:NativeStackScreenProps<RootParams,'Review'>){const{caseId}=useRegistrationCase();const query=useQuery({queryKey:['application',caseId],queryFn:()=>driverRegService.application(caseId!),enabled:!!caseId});return <Screen title="Review application" eyebrow="Before submission"><ErrorSummary message={query.error?.message}/><Text style={s.lead}>Submission locks the applicant snapshot for independent Admin review. Approval is never automatic.</Text>{query.data?steps.map(item=><StepRow key={item.key} label={item.label} icon={item.icon} state={query.data.steps?.[item.key]?'complete':'pending'}/>):null}<PrimaryButton label="Continue to submission" onPress={()=>navigation.navigate('Submit')}/></Screen>}

export function SubmitScreen({navigation}:NativeStackScreenProps<RootParams,'Submit'>){const{caseId}=useRegistrationCase();const[error,setError]=useState('');const mutation=useMutation({mutationFn:()=>driverRegService.submit(caseId!,`${Date.now()}-${Math.random().toString(36).slice(2)}`),onSuccess:app=>{if(app.status!=='submitted'){setError('The API did not confirm submission. Refresh the application before retrying.');return;}navigation.replace('Status');},onError:e=>setError(e.message)});return <Screen title="Submit application" eyebrow="Final confirmation"><ErrorSummary message={error}/><Text style={s.lead}>Admin independently reviews the applicant identity and evidence. A correction may be requested.</Text><PrimaryButton label={mutation.isPending?'Submitting…':'Submit for independent review'} disabled={mutation.isPending} onPress={()=>mutation.mutate()}/></Screen>}

export function StatusScreen({navigation}:NativeStackScreenProps<RootParams,'Status'>){const{caseId}=useRegistrationCase();const query=useQuery({queryKey:['application',caseId],queryFn:()=>driverRegService.application(caseId!),enabled:!!caseId,refetchInterval:30000});const app=query.data;if(!app)return <Screen title="Application status"><ErrorSummary message={query.error?.message}/><PrimaryButton label="Retry" onPress={()=>query.refetch()}/></Screen>;return <Screen title="Application status" eyebrow={app.status.replaceAll('_',' ')}><Text style={s.lead}>Application {app.id}</Text>{['submitted','under_review','documents_requested','verification','approved'].map(state=><View key={state} style={s.timeline}><View style={[s.dot,app.status===state&&s.dotActive]}/><Text style={[s.timelineText,app.status===state&&s.bold]}>{state.replaceAll('_',' ')}</Text></View>)}{app.decision_reason?<ErrorSummary message={app.decision_reason}/>:null}{app.status==='approved'?<PrimaryButton label="Continue to Driver activation" tone="yellow" onPress={()=>navigation.navigate('Activation')}/>:null}{app.status==='documents_requested'?<PrimaryButton label="Fix requested items" onPress={()=>navigation.navigate('Home')}/>:null}</Screen>}

export function ActivationScreen(){const open=async()=>{if(await Linking.canOpenURL(environment.driverAppScheme))await Linking.openURL(environment.driverAppScheme);};return <Screen title="Ready for activation" eyebrow="Application approved"><Text style={s.lead}>DriverReg never registers an operational Driver-app session. The approved driver signs in to the Driver app with their verified phone and OTP.</Text><PrimaryButton tone="yellow" label="Open LaBar Driver App" onPress={open}/></Screen>}

const s=StyleSheet.create({lead:{fontSize:15,lineHeight:23,color:colors.secondaryText,marginBottom:24},muted:{color:colors.secondaryText,lineHeight:21},progress:{alignItems:'center',padding:22,borderRadius:20,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,marginBottom:16},progressValue:{fontSize:34,fontWeight:'900',color:colors.primary},space:{height:20},age:{marginTop:-8,marginBottom:20,color:colors.secondaryText},timeline:{minHeight:52,flexDirection:'row',alignItems:'center',gap:14,borderLeftWidth:2,borderLeftColor:colors.border,marginLeft:9,paddingLeft:20},dot:{width:12,height:12,borderRadius:6,backgroundColor:'#B8B5B0',position:'absolute',left:-7},dotActive:{backgroundColor:colors.primary},timelineText:{textTransform:'capitalize',color:colors.secondaryText},bold:{fontWeight:'800',color:colors.text}});
